"""Conversation history management and compaction service.

Implements:
- Rolling summary generation
- Message threshold detection
- Compacted history assembly
"""
from typing import List, Dict, Optional, Tuple
from datetime import datetime


# Message count threshold before compaction triggers
MESSAGE_THRESHOLD = 20

# Approximate tokens per message for estimation
AVG_TOKENS_PER_MESSAGE = 150


def should_compact_history(message_count: int) -> bool:
    """
    Determine if conversation history should be compacted.

    Args:
        message_count: Number of messages in conversation

    Returns:
        True if compaction should occur
    """
    return message_count > MESSAGE_THRESHOLD


def estimate_token_count(messages: List[Dict]) -> int:
    """
    Rough estimation of token count for messages.

    Args:
        messages: List of message dictionaries

    Returns:
        Estimated token count
    """
    # Simple estimation: count characters and divide by 4
    # (rough approximation of token count)
    total_chars = sum(
        len(str(msg.get("content", "")))
        for msg in messages
    )
    return total_chars // 4


def generate_summary_prompt(messages: List[Dict]) -> str:
    """
    Generate a prompt for summarizing conversation history.

    Args:
        messages: Messages to summarize

    Returns:
        Summary generation prompt
    """
    return f"""Summarize this conversation history in 2-3 paragraphs:

- Focus on key decisions and outcomes
- Preserve important context for future turns
- Include user goals and current progress
- Note any pending tasks or blockers

Keep the summary concise but comprehensive.

Conversation ({len(messages)} messages):
---
{_format_messages_for_summary(messages)}
---

Provide a rolling summary:"""


def _format_messages_for_summary(messages: List[Dict]) -> str:
    """Format messages for summary generation."""
    formatted = []
    for msg in messages:
        role = msg.get("role", "unknown")
        content = str(msg.get("content", ""))[:500]  # Truncate long messages
        formatted.append(f"{role.upper()}: {content}")

    return "\n\n".join(formatted)


def create_summary_message(summary_text: str) -> Dict:
    """
    Create a system message containing conversation summary.

    Args:
        summary_text: The generated summary

    Returns:
        Message dictionary with summary
    """
    return {
        "role": "system",
        "content": f"""# Conversation Summary

{summary_text}

---
*This is a rolling summary of prior conversation. Recent messages follow below.*
""",
        "is_summary": True,
        "created_at": datetime.utcnow().isoformat(),
    }


def compact_history(
    messages: List[Dict],
    keep_recent: int = 10,
    summary_text: Optional[str] = None,
) -> Tuple[List[Dict], Dict]:
    """
    Compact conversation history using rolling summary.

    Args:
        messages: Full message history
        keep_recent: Number of recent messages to keep verbatim
        summary_text: Optional pre-generated summary

    Returns:
        Tuple of (compacted_messages, stats)
    """
    if len(messages) <= keep_recent:
        return messages, {"compacted": False}

    # Split messages into old (to summarize) and recent (to keep)
    split_point = len(messages) - keep_recent
    old_messages = messages[:split_point]
    recent_messages = messages[split_point:]

    # Create summary message
    if summary_text is None:
        summary_text = "[Summary placeholder - will be generated by model]"

    summary_msg = create_summary_message(summary_text)

    # Assemble compacted history: summary + recent messages
    compacted = [summary_msg] + recent_messages

    # Calculate stats
    stats = {
        "compacted": True,
        "original_count": len(messages),
        "compacted_count": len(compacted),
        "messages_summarized": len(old_messages),
        "messages_kept": len(recent_messages),
        "original_tokens": estimate_token_count(messages),
        "compacted_tokens": estimate_token_count(compacted),
    }

    return compacted, stats


def extract_recent_messages(
    messages: List[Dict],
    count: int = 10,
) -> List[Dict]:
    """
    Extract most recent N messages from history.

    Args:
        messages: Full message history
        count: Number of recent messages to extract

    Returns:
        List of recent messages
    """
    if len(messages) <= count:
        return messages

    return messages[-count:]


def prepare_messages_for_api(
    messages: List[Dict],
    use_compaction: bool = True,
    summary_text: Optional[str] = None,
) -> Tuple[List[Dict], Dict]:
    """
    Prepare conversation messages for API call.

    Applies compaction if enabled and threshold is met.

    Args:
        messages: Full message history
        use_compaction: Whether to enable automatic compaction
        summary_text: Optional pre-generated summary

    Returns:
        Tuple of (prepared_messages, metadata)
    """
    metadata = {
        "compaction_enabled": use_compaction,
        "original_count": len(messages),
    }

    if not use_compaction:
        metadata["compacted"] = False
        return messages, metadata

    if not should_compact_history(len(messages)):
        metadata["compacted"] = False
        metadata["reason"] = "below_threshold"
        return messages, metadata

    # Apply compaction
    compacted, stats = compact_history(
        messages,
        keep_recent=10,
        summary_text=summary_text,
    )

    metadata.update(stats)
    return compacted, metadata


# ==============================================================================
# Message filtering and transformation
# ==============================================================================

def filter_system_messages(messages: List[Dict]) -> List[Dict]:
    """Remove system messages (except summaries) from history."""
    return [
        msg for msg in messages
        if msg.get("role") != "system" or msg.get("is_summary", False)
    ]


def normalize_message_roles(messages: List[Dict]) -> List[Dict]:
    """
    Ensure messages alternate properly between user and assistant.

    Claude API requires messages to alternate between user and assistant.
    """
    if not messages:
        return messages

    normalized = []
    last_role = None

    for msg in messages:
        role = msg.get("role")

        # Skip if same role as previous (unless it's a summary)
        if role == last_role and not msg.get("is_summary", False):
            continue

        normalized.append(msg)
        last_role = role

    return normalized


def build_conversation_context(
    messages: List[Dict],
    max_context_messages: int = 50,
) -> List[Dict]:
    """
    Build conversation context for current turn.

    Args:
        messages: Full message history
        max_context_messages: Maximum messages to include

    Returns:
        Context messages for API call
    """
    # Limit context window
    if len(messages) > max_context_messages:
        messages = messages[-max_context_messages:]

    # Filter and normalize
    messages = filter_system_messages(messages)
    messages = normalize_message_roles(messages)

    return messages
