"""add workflow and metrics models

Revision ID: c57565c485d3
Revises:
Create Date: 2026-04-30 16:02:02.349073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'c57565c485d3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create enum types if they don't exist
    conn = op.get_bind()

    # Check if workflowcategory enum exists
    result = conn.execute(sa.text(
        "SELECT 1 FROM pg_type WHERE typname = 'workflowcategory'"
    )).fetchone()
    if not result:
        workflowcategory = postgresql.ENUM('WORKFLOW', 'QUESTION', 'BUG_FIX', 'FEATURE', 'ANALYSIS', 'CREATIVE', 'ADMIN', 'UNKNOWN', name='workflowcategory', create_type=False)
        workflowcategory.create(conn, checkfirst=True)

    # Check if workflowrunstatus enum exists
    result = conn.execute(sa.text(
        "SELECT 1 FROM pg_type WHERE typname = 'workflowrunstatus'"
    )).fetchone()
    if not result:
        workflowrunstatus = postgresql.ENUM('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='workflowrunstatus', create_type=False)
        workflowrunstatus.create(conn, checkfirst=True)

    # Check if stepstatus enum exists
    result = conn.execute(sa.text(
        "SELECT 1 FROM pg_type WHERE typname = 'stepstatus'"
    )).fetchone()
    if not result:
        stepstatus = postgresql.ENUM('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'SKIPPED', name='stepstatus', create_type=False)
        stepstatus.create(conn, checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('workflow_category', postgresql.ENUM('WORKFLOW', 'QUESTION', 'BUG_FIX', 'FEATURE', 'ANALYSIS', 'CREATIVE', 'ADMIN', 'UNKNOWN', name='workflowcategory', create_type=False), nullable=False),
    sa.Column('definition', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_workflow_template_name')
    )
    op.create_index(op.f('ix_workflow_templates_id'), 'workflow_templates', ['id'], unique=False)
    op.create_index(op.f('ix_workflow_templates_name'), 'workflow_templates', ['name'], unique=False)
    op.create_table('failed_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('run_id', sa.String(length=255), nullable=True),
    sa.Column('error_type', sa.String(length=100), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('original_message_count', sa.Integer(), nullable=False),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_failed_runs_created_at'), 'failed_runs', ['created_at'], unique=False)
    op.create_index(op.f('ix_failed_runs_error_type'), 'failed_runs', ['error_type'], unique=False)
    op.create_index(op.f('ix_failed_runs_id'), 'failed_runs', ['id'], unique=False)
    op.create_index(op.f('ix_failed_runs_run_id'), 'failed_runs', ['run_id'], unique=False)
    op.create_index(op.f('ix_failed_runs_session_id'), 'failed_runs', ['session_id'], unique=False)
    op.create_table('workflow_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='workflowrunstatus', create_type=False), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('current_state', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['workflow_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_runs_id'), 'workflow_runs', ['id'], unique=False)
    op.create_index(op.f('ix_workflow_runs_session_id'), 'workflow_runs', ['session_id'], unique=False)
    op.create_index(op.f('ix_workflow_runs_status'), 'workflow_runs', ['status'], unique=False)
    op.create_index(op.f('ix_workflow_runs_template_id'), 'workflow_runs', ['template_id'], unique=False)
    op.create_table('workflow_step_executions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_run_id', sa.Integer(), nullable=False),
    sa.Column('step_id', sa.String(length=255), nullable=False),
    sa.Column('step_name', sa.String(length=500), nullable=False),
    sa.Column('step_type', sa.String(length=100), nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'SKIPPED', name='stepstatus', create_type=False), nullable=False),
    sa.Column('input_data', sa.JSON(), nullable=True),
    sa.Column('output_data', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['workflow_run_id'], ['workflow_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_step_executions_id'), 'workflow_step_executions', ['id'], unique=False)
    op.create_index(op.f('ix_workflow_step_executions_status'), 'workflow_step_executions', ['status'], unique=False)
    op.create_index(op.f('ix_workflow_step_executions_workflow_run_id'), 'workflow_step_executions', ['workflow_run_id'], unique=False)
    op.create_table('llm_decision_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_run_id', sa.Integer(), nullable=False),
    sa.Column('step_execution_id', sa.Integer(), nullable=False),
    sa.Column('step_name', sa.String(length=255), nullable=False),
    sa.Column('decision_point', sa.String(length=255), nullable=False),
    sa.Column('prompt_template_id', sa.String(length=100), nullable=True),
    sa.Column('prompt_hash', sa.String(length=64), nullable=True),
    sa.Column('model_used', sa.String(length=100), nullable=False),
    sa.Column('response_raw', sa.Text(), nullable=True),
    sa.Column('decision_parsed', sa.Text(), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('llm_reasoning', sa.Text(), nullable=True),
    sa.Column('human_feedback', sa.String(length=50), nullable=True),
    sa.Column('outcome_quality', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['step_execution_id'], ['workflow_step_executions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_run_id'], ['workflow_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_decision_metrics_decision_point'), 'llm_decision_metrics', ['decision_point'], unique=False)
    op.create_index(op.f('ix_llm_decision_metrics_human_feedback'), 'llm_decision_metrics', ['human_feedback'], unique=False)
    op.create_index(op.f('ix_llm_decision_metrics_id'), 'llm_decision_metrics', ['id'], unique=False)
    op.create_index(op.f('ix_llm_decision_metrics_prompt_hash'), 'llm_decision_metrics', ['prompt_hash'], unique=False)
    op.create_index(op.f('ix_llm_decision_metrics_prompt_template_id'), 'llm_decision_metrics', ['prompt_template_id'], unique=False)
    op.create_index(op.f('ix_llm_decision_metrics_step_execution_id'), 'llm_decision_metrics', ['step_execution_id'], unique=False)
    op.create_index(op.f('ix_llm_decision_metrics_step_name'), 'llm_decision_metrics', ['step_name'], unique=False)
    op.create_index(op.f('ix_llm_decision_metrics_workflow_run_id'), 'llm_decision_metrics', ['workflow_run_id'], unique=False)
    op.create_table('step_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_run_id', sa.Integer(), nullable=False),
    sa.Column('step_execution_id', sa.Integer(), nullable=False),
    sa.Column('step_name', sa.String(length=255), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', postgresql.ENUM('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'SKIPPED', name='stepstatus', create_type=False), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['step_execution_id'], ['workflow_step_executions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_run_id'], ['workflow_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_step_metrics_id'), 'step_metrics', ['id'], unique=False)
    op.create_index(op.f('ix_step_metrics_status'), 'step_metrics', ['status'], unique=False)
    op.create_index(op.f('ix_step_metrics_step_execution_id'), 'step_metrics', ['step_execution_id'], unique=False)
    op.create_index(op.f('ix_step_metrics_step_name'), 'step_metrics', ['step_name'], unique=False)
    op.create_index(op.f('ix_step_metrics_workflow_run_id'), 'step_metrics', ['workflow_run_id'], unique=False)
    op.add_column('sessions', sa.Column('session_summary', sa.Text(), nullable=True))
    op.add_column('sessions', sa.Column('summary_generated_at', sa.DateTime(), nullable=True))
    op.add_column('sessions', sa.Column('message_count_at_summary', sa.Integer(), nullable=True, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'message_count_at_summary')
    op.drop_column('sessions', 'summary_generated_at')
    op.drop_column('sessions', 'session_summary')
    op.drop_index(op.f('ix_step_metrics_workflow_run_id'), table_name='step_metrics')
    op.drop_index(op.f('ix_step_metrics_step_name'), table_name='step_metrics')
    op.drop_index(op.f('ix_step_metrics_step_execution_id'), table_name='step_metrics')
    op.drop_index(op.f('ix_step_metrics_status'), table_name='step_metrics')
    op.drop_index(op.f('ix_step_metrics_id'), table_name='step_metrics')
    op.drop_table('step_metrics')
    op.drop_index(op.f('ix_llm_decision_metrics_workflow_run_id'), table_name='llm_decision_metrics')
    op.drop_index(op.f('ix_llm_decision_metrics_step_name'), table_name='llm_decision_metrics')
    op.drop_index(op.f('ix_llm_decision_metrics_step_execution_id'), table_name='llm_decision_metrics')
    op.drop_index(op.f('ix_llm_decision_metrics_prompt_template_id'), table_name='llm_decision_metrics')
    op.drop_index(op.f('ix_llm_decision_metrics_prompt_hash'), table_name='llm_decision_metrics')
    op.drop_index(op.f('ix_llm_decision_metrics_id'), table_name='llm_decision_metrics')
    op.drop_index(op.f('ix_llm_decision_metrics_human_feedback'), table_name='llm_decision_metrics')
    op.drop_index(op.f('ix_llm_decision_metrics_decision_point'), table_name='llm_decision_metrics')
    op.drop_table('llm_decision_metrics')
    op.drop_index(op.f('ix_workflow_step_executions_workflow_run_id'), table_name='workflow_step_executions')
    op.drop_index(op.f('ix_workflow_step_executions_status'), table_name='workflow_step_executions')
    op.drop_index(op.f('ix_workflow_step_executions_id'), table_name='workflow_step_executions')
    op.drop_table('workflow_step_executions')
    op.drop_index(op.f('ix_workflow_runs_template_id'), table_name='workflow_runs')
    op.drop_index(op.f('ix_workflow_runs_status'), table_name='workflow_runs')
    op.drop_index(op.f('ix_workflow_runs_session_id'), table_name='workflow_runs')
    op.drop_index(op.f('ix_workflow_runs_id'), table_name='workflow_runs')
    op.drop_table('workflow_runs')
    op.drop_index(op.f('ix_failed_runs_session_id'), table_name='failed_runs')
    op.drop_index(op.f('ix_failed_runs_run_id'), table_name='failed_runs')
    op.drop_index(op.f('ix_failed_runs_id'), table_name='failed_runs')
    op.drop_index(op.f('ix_failed_runs_error_type'), table_name='failed_runs')
    op.drop_index(op.f('ix_failed_runs_created_at'), table_name='failed_runs')
    op.drop_table('failed_runs')
    op.drop_index(op.f('ix_workflow_templates_name'), table_name='workflow_templates')
    op.drop_index(op.f('ix_workflow_templates_id'), table_name='workflow_templates')
    op.drop_table('workflow_templates')

    # Drop enum types
    conn = op.get_bind()
    conn.execute(sa.text("DROP TYPE IF EXISTS stepstatus"))
    conn.execute(sa.text("DROP TYPE IF EXISTS workflowrunstatus"))
    conn.execute(sa.text("DROP TYPE IF EXISTS workflowcategory"))
    # ### end Alembic commands ###
