"""Add RBAC authentication fields to User model

Revision ID: eac10a7850ae
Revises: 556307633534
Create Date: 2026-06-09 10:04:13.702969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eac10a7850ae'
down_revision: Union[str, Sequence[str], None] = '556307633534'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_workflow_outcomes_created_at'), table_name='workflow_outcomes')
    op.drop_index(op.f('idx_workflow_outcomes_user_id'), table_name='workflow_outcomes')
    op.drop_index(op.f('idx_workflow_outcomes_workflow_type'), table_name='workflow_outcomes')
    op.drop_table('workflow_outcomes')
    op.drop_index(op.f('ix_mcp_integrations_tenant_id_integration_name'), table_name='mcp_integrations')
    op.add_column('tenant_skills', sa.Column('timeout_seconds', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('auth_source', sa.Enum('LOCAL', 'SSO', 'TEESHEET_EMBED', name='authsource'), nullable=False, server_default='LOCAL'))
    op.add_column('users', sa.Column('external_id', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('sso_claims', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('club_context', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('last_login', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_users_external_id'), 'users', ['external_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_external_id'), table_name='users')
    op.drop_column('users', 'last_login')
    op.drop_column('users', 'club_context')
    op.drop_column('users', 'sso_claims')
    op.drop_column('users', 'external_id')
    op.drop_column('users', 'auth_source')
    op.drop_column('tenant_skills', 'timeout_seconds')
    op.create_index(op.f('ix_mcp_integrations_tenant_id_integration_name'), 'mcp_integrations', ['tenant_id', 'integration_name'], unique=False)
    op.create_table('workflow_outcomes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('workflow_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('outcome', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('context', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('workflow_outcomes_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('workflow_outcomes_pkey'))
    )
    op.create_index(op.f('idx_workflow_outcomes_workflow_type'), 'workflow_outcomes', ['workflow_type'], unique=False)
    op.create_index(op.f('idx_workflow_outcomes_user_id'), 'workflow_outcomes', ['user_id'], unique=False)
    op.create_index(op.f('idx_workflow_outcomes_created_at'), 'workflow_outcomes', ['created_at'], unique=False)
    # ### end Alembic commands ###
